### ISSUE TITLE
Release snap(off topic)

### ISSUE THREAD

**Issue by soumyaDghosh** [headsetapp/headset-snap#7]
Hey I know this is off-topic, but I am builing a snap for an app, but I am not able to release it. It's getting rejected everytime. Can you help me in releasing my first snap?

**Comment by fcastilloec** [comment]
I can do my best to help but I'm no expert with snaps. It'll be better if you join our Slack and just message me there. It'll be easier to have a conversation and even help with code, etc.
Here's Headset's slack: https://tinyurl.com/y7m8y5x4

**Comment by soumyaDghosh** [comment]
Hey please resend the link, probably it's expired. I was busy for my exams. Also, new to slack :(

**Comment by fcastilloec** [comment]
Here's an updated link: https://tinyurl.com/8ejkcdac
The link can only be used for a maximum number of people. Thanks for pointing it out, I also updated it on our README
